### ISSUE TITLE
Cannot run script on different device

### ISSUE THREAD

**Issue by craigtaverner** [mapillary/mapillary_tools#10]
If the script and the files are not on the same device:

    Exception in thread Thread-2:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
        self.run()
      File "/home/craig/dev/GoPro/mapillary_tools/python/upload.py", line 183, in run
        upload_file(filepath, **self.params)
      File "/home/craig/dev/GoPro/mapillary_tools/python/upload.py", line 123, in upload_file
        os.rename(filepath, "success/"+filename)
    OSError: [Errno 18] Invalid cross-device link

**Comment by scaidermern** [comment]
This issue isn't really fixed, is it? I'm still experiencing this issue.

```
Traceback (most recent call last):
  File "./remove_duplicates.py", line 417, in <module>
    image_remover.do_magic()
  File "./remove_duplicates.py", line 268, in do_magic
    self._handle_possible_duplicate(file_path, exif_reader)
  File "./remove_duplicates.py", line 284, in _handle_possible_duplicate
    self._move_into_duplicate_dir(file_path)
  File "./remove_duplicates.py", line 233, in _move_into_duplicate_dir
    self._move_into_dir(file, self._duplicate_dir)
  File "./remove_duplicates.py", line 240, in _move_into_dir
    os.rename(file, os.path.join(dir, filename))
OSError: [Errno 18] Invalid cross-device link
```

Modifying the script is not a valid solution. Please re-open.
