### ISSUE TITLE
AttributeError: close from remove_duplicates.py

### ISSUE THREAD

**Issue by pnorman** [mapillary/mapillary_tools#100]
```
pnorman@pippin:~/osm/photos/20151028/01$ python ~/osm/photos/mapillary_tools/python/remove_duplicates.py -n -d 4 . duplicate
Traceback (most recent call last):
  File "/home/pnorman/osm/photos/mapillary_tools/python/remove_duplicates.py", line 417, in <module>
    image_remover.do_magic()
  File "/home/pnorman/osm/photos/mapillary_tools/python/remove_duplicates.py", line 262, in do_magic
    capturetime, files = self._sort_file_list(files)
  File "/home/pnorman/osm/photos/mapillary_tools/python/remove_duplicates.py", line 251, in _sort_file_list
    capture_times = [self._read_capture_time(filepath) for filepath in file_list]
  File "/home/pnorman/osm/photos/mapillary_tools/python/remove_duplicates.py", line 244, in _read_capture_time
    reader = PILExifReader(filepath)
  File "/home/pnorman/osm/photos/mapillary_tools/python/lib/exif_pil.py", line 24, in __init__
    image.close()
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 528, in __getattr__
    raise AttributeError(name)
```

The PIL installed is from the Pillow fork, and the PIL version is 2.3.0-1ubuntu3

**Comment by pnorman** [comment]
With a clean install in a virtualenv I get PIL 3.0 and don't get this error, but I instead get #101
