### ISSUE TITLE
add_mapillary_tag_from_exif.py fails on something something ssl certificate

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_tools#118]
I ran `add_mapillary_tag_from_exif.py` and got the following output:

```
Traceback (most recent call last):
  File "add_mapillary_tag_from_exif.py", line 62, in <module>
    upload_token = get_upload_token(MAPILLARY_EMAIL, MAPILLARY_PASSWORD)
  File "/home/ruurd/DCIM/python/lib/uploader.py", line 134, in get_upload_token
    response = urllib.urlopen("https://api.mapillary.com/v1/u/login", params)
  File "/usr/lib/python2.7/urllib.py", line 89, in urlopen
    return opener.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 215, in open
    return getattr(self, name)(url, data)
  File "/usr/lib/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1278, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 352, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 597, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 826, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```
On monday everything was working fine. I also tried the most recent version of the tools, but same result.

my guess is that it's related to https://github.com/mapillary/mapillary_issues/issues/1923

**Comment by ybkuang** [comment]
@peterneubauer can you help take a look at this?

**Comment by peterneubauer** [comment]
Yup, on it ....

**Comment by peterneubauer** [comment]
Can you pull the latest changes and try again? We updated the SSL cert, and want to use a.mapillary.com ...

**Comment by de-vries** [comment]
check
