### ISSUE TITLE
running upload.py under linux (ubuntu trusty) not work

### ISSUE THREAD

**Issue by msevilla00** [mapillary/mapillary_tools#137]
I download full repository and I'm trying to use upload.py script in my pc under ubuntu mate (14.04 - trusty) and I get this message: 

```
user@computer:~/git/mapillary_tools/python $ python upload.py ~/mapillary/2016_09_01_10_52_42_467___Mapillary
 Traceback (most recent call last):
   File "upload.py", line 6, in <module>
     from lib.uploader import upload_file_list
   File "/home/miguel/git/mapillary_tools/python/lib/uploader.py", line 1, in <module>
     from lib.exif import EXIF
   File "/home/miguel/git/mapillary_tools/python/lib/exif.py", line 4, in <module>
     import exifread
 ImportError: No module named exifread
```

No idea where to find exifread module.
Any suggestion?

**Comment by msevilla00** [comment]
I solved installing the requeriments and it works
The key was to type:
`sudo sudo pip install -r requirements.txt`
An then:
`python upload.py ~/mapillary/2016_09_01_10_52_42_467___Mapillary`
Cheers
