### ISSUE TITLE
pyexiv2 not found on brew with El Capitan

### ISSUE THREAD

**Issue by nighto** [mapillary/mapillary_tools#143]
Hello, I'm having some troubles with `pyexiv2` on El Capitan. It is available on `brew`, I can install it correctly, but then `python` doesn't find it.

I've seen [some instructions](http://stackoverflow.com/questions/16623902/pyexiv2-with-homebrew-python-2-7-4) saying that you have to compile `boost` in order to install `pyexiv2` correctly. Did that, but the error persists. What else can I try?

The error is:

```
/usr/local/Cellar/pyexiv2/0.3.2_1: 14 files, 574K
MacBook-Pro-de-Arlindo:360T0041 nighto$ python ~/Downloads/mapillary_tools-master/python/interpolate_direction.py .
Traceback (most recent call last):
  File "/Users/nighto/Downloads/mapillary_tools-master/python/interpolate_direction.py", line 3, in <module>
    import os, sys, pyexiv2
ImportError: No module named pyexiv2
MacBook-Pro-de-Arlindo:360T0041 nighto$ export PYTHONPATH=$PYTHONPATH:/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
MacBook-Pro-de-Arlindo:360T0041 nighto$ python ~/Downloads/mapillary_tools-master/python/interpolate_direction.py .
Traceback (most recent call last):
  File "/Users/nighto/Downloads/mapillary_tools-master/python/interpolate_direction.py", line 3, in <module>
    import os, sys, pyexiv2
ImportError: No module named pyexiv2
```

**Comment by nighto** [comment]
Guess I should had more attention to `brew` installation output. It says:

```
==> Caveats
Python modules have been installed and Homebrew's site-packages is not
in your Python sys.path, so you will not be able to import the modules
this formula installed. If you plan to develop with these modules,
please run:
  mkdir -p /Users/nighto/Library/Python/2.7/lib/python/site-packages
  echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/nighto/Library/Python/2.7/lib/python/site-packages/homebrew.pth
```

Did that and it run fine.
