### ISSUE TITLE
NameError cast in geotag_from_gpx.py

### ISSUE THREAD

**Issue by Skippern** [mapillary/mapillary_tools#178]
```
===
Traceback (most recent call last):
  File "mapillary_tools/python//geotag_from_gpx.py", line 140, in <module>
    add_exif_using_timestamp(filepath, filetime, gpx, args.time_offset, args.bearing_offset)
  File "mapillary_tools/python//geotag_from_gpx.py", line 49, in add_exif_using_timestamp
    print("Added geodata to: {}  time {}  lat {}  lon {}  alt {}  bearing {}".format(filename, time, lat, lon, elevation, exiv_bearing))
NameError: global name 'exiv_bearing' is not defined
```
Typo in variable name? Changing `exiv_bearing` to `corrected_bearing` in line 49 solved it for me

**Comment by ybkuang** [comment]
@Skippern Thanks. That slipped through during the refactoring. We will be adding tests to the codes soon so things will be more consistent.
