### ISSUE TITLE
Unable to upload files - lib.pexif.InvalidFile: Unable to find EOI marker.

### ISSUE THREAD

**Issue by pschonmann** [mapillary/mapillary_tools#185]
~/apps/mapillary_tools/python# ./upload_with_preprocessing.py --interpolate_directions ~/Desktop/Cyklo/

=== Spliting photos into sequences based on time and distance ...
Moved 1001 photos to ~/Desktop/Cyklo/0
Moved 390 photos to ~/Desktop/Cyklo/1
Moved 711 photos to ~/Desktop/Cyklo/2
Moved 129 photos to ~/Desktop/Cyklo/3
Moved 1001 photos to ~/Desktop/Cyklo/4
Moved 351 photos to ~/Desktop/Cyklo/5
Done split photos in ~/Desktop/Cyklo/ into 6 sequences

=== Adding Mapillary tags and uploading per sequence ...

=== Interpolating direction per sequence ...

=== Interpolating timestamps per sequence ...
  sequence uuid: 9efc5409-1171-49c5-8078-749a26c21978
[============================================================] 99.7% Adding Mapillary tags
=== Interpolating direction per sequence ...

=== Interpolating timestamps per sequence ...
  sequence uuid: 0baa5037-0706-4227-9c55-5f4b534707bc
[============================================================] 99.9% Adding Mapillary tags
=== Interpolating direction per sequence ...

=== Interpolating timestamps per sequence ...
  sequence uuid: 808f2e1d-7b28-4a68-a3ff-d7ecd20f4858
[============================================================] 99.9% Adding Mapillary tags
=== Interpolating direction per sequence ...

=== Interpolating timestamps per sequence ...
  sequence uuid: 0cc5266e-0d26-4d59-a8dd-ea551de20701
Traceback (most recent call last):---------------------------] 2.8% Adding Mapillary tags
  File "./upload_with_preprocessing.py", line 258, in <module>
    external_properties)
  File "~/apps/mapillary_tools/python/lib/exifedit.py", line 81, in create_mapillary_description
    metadata = ExifEdit(filename)
  File "~/apps/mapillary_tools/python/lib/exifedit.py", line 140, in __init__
    self.ef = JpegFile.fromFile(filename)
  File "~/apps/mapillary_tools/python/lib/pexif.py", line 954, in fromFile
    return JpegFile(f, filename=filename, mode=mode)
  File "~/apps/mapillary_tools/python/lib/pexif.py", line 1017, in __init__
    attempt = segment_class(mark, input, data, self.mode)
  File "~/apps/mapillary_tools/python/lib/pexif.py", line 181, in __init__
    raise JpegFile.InvalidFile("Unable to find EOI marker.")
lib.pexif.InvalidFile: Unable to find EOI marker.

**Comment by ybkuang** [comment]
@pschonmann can you share two of the images to yubin [at] mapillary [dot] com? I will take a look.

**Comment by mishari** [comment]
I had some truncated jpg files that caused this error. Try to repeat it by taking a large jpg file (say 3 megabytes) and doing dd if=input.jpg if=output.jpg bs=1m count=1

**Comment by jernejaMislej** [comment]
@pschonmann  hi, sorry for not getting back to you on this issue.
we have replaced the exif library, which is now able to handle images like yours, so hopefully you will not experience any more issues.

if you have any more problems with your imports please get back to us, otherwise I will close this issue
