### ISSUE TITLE
Download URL broken

### ISSUE THREAD

**Issue by domdomegg** [mapillary/mapillary_tools#187]
https://a.mapillary.com/v1/im/search?download used in [download_images.py](https://github.com/mapillary/mapillary_tools/blob/master/python/download_images.py) returns a `404` error.

```
Traceback (most recent call last):
  File "download_images.py", line 78, in <module>
    query = query_search_api(args.min_lat, args.max_lat, args.min_lon, args.max_lon, args.max_results)
  File "download_images.py", line 31, in query_search_api
    query = urllib2.urlopen(MAPILLARY_API_IM_SEARCH_URL + params).read()
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

**Comment by peterneubauer** [comment]
Yes, this URL should be updated to version 3.

**Comment by domdomegg** [comment]
Basically done it now - will submit pull request shortly
