### ISSUE TITLE
Error looking up size (pexif.py)

### ISSUE THREAD

**Issue by mprins** [mapillary/mapillary_tools#190]
It seems the `ExifType.lookup` dict is missing some values, specifically `8` 

I''m seeing the below stacktrace:

```
python2 ~/workspace/mapillary_tools/python/interpolate_direction.py ./2017_04_27_15_32_53_172/
Traceback (most recent call last):
  File "/home/mark/workspace/mapillary_tools/python/interpolate_direction.py", line 57, in <module>
    write_direction_to_image(image_name, bearing)
  File "/home/mark/workspace/mapillary_tools/python/interpolate_direction.py", line 30, in write_direction_to_image
    exif = ExifEdit(filename)
  File "/home/mark/workspace/mapillary_tools/python/lib/exifedit.py", line 164, in __init__
    self.ef = JpegFile.fromFile(filename)
  File "/home/mark/workspace/mapillary_tools/python/lib/pexif.py", line 960, in fromFile
    return JpegFile(f, filename=filename, mode=mode)
  File "/home/mark/workspace/mapillary_tools/python/lib/pexif.py", line 1023, in __init__
    attempt = segment_class(mark, input, data, self.mode)
  File "/home/mark/workspace/mapillary_tools/python/lib/pexif.py", line 810, in __init__
    DefaultSegment.__init__(self, marker, fd, data, mode)
  File "/home/mark/workspace/mapillary_tools/python/lib/pexif.py", line 125, in __init__
    self.parse_data(data)
  File "/home/mark/workspace/mapillary_tools/python/lib/pexif.py", line 854, in parse_data
    ifd = IfdTIFF(self.e, offset, self, self.mode, tiff_data)
  File "/home/mark/workspace/mapillary_tools/python/lib/pexif.py", line 368, in __init__
    exif_type_size(exif_type), components,
  File "/home/mark/workspace/mapillary_tools/python/lib/pexif.py", line 221, in exif_type_size
    return ExifType.lookup.get(exif_type).size
AttributeError: 'NoneType' object has no attribute 'size'

```
some print statements show that there is a size lookup for a value of 8

**Comment by ybkuang** [comment]
Noted @mprins. We are looking into replacing pexif. Sorry about the inconveniences.

**Comment by ybkuang** [comment]
Similar issues [here](https://forum.mapillary.com/t/running-the-python-scripts/130/61?)

**Comment by ybkuang** [comment]
@mprins This is related to the exif library. We have been working on a fix for it. We want to test if the fix works or not on your images. Can you send a few (1-2) sample images to yubin at mapillary dot com

**Comment by mprins** [comment]
sent mail and attached here as well.

[2017_04_27_15_32_53_172.zip](https://github.com/mapillary/mapillary_tools/files/1487795/2017_04_27_15_32_53_172.zip)

**Comment by jernejaMislej** [comment]
hi,
sorry for not getting back to you on this.
We have replaced the EXIF editing library, which is now able to handle these images.
Also letting you know we have released a new version of the tools. Usage instructions and details in the [README](https://github.com/mapillary/mapillary_tools/blob/master/README.md)
Hopefully you will be able to upload images more smoothly now, if not, let us know
