### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by alexandrz** [mapillary/mapillary_tools#192]
Can not upload photos:

```
Traceback (most recent call last):
  File "mapillary_tools/python/upload_with_preprocessing.py", line 133, in <module>
    upload_token = get_upload_token(MAPILLARY_EMAIL, MAPILLARY_PASSWORD)
  File "/Mapillary/mapillary_tools/python/lib/uploader.py", line 135, in get_upload_token
    resp = json.loads(response.read())
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by alexandrz** [comment]
Debugged it a little bit. It looks like the login endpoint ( https://a.mapillary.com/v1/u/login ) returns 404.

**Comment by alexandrz** [comment]
Fixed after updating scripts
