### ISSUE TITLE
lib.pexif.InvalidFile: Unable to find EOI marker.

### ISSUE THREAD

**Issue by mishari** [mapillary/mapillary_tools#198]
add_mapillary_tag_from_exif.py fails with the following traceback:

```
Traceback (most recent call last):
  File "/Users/mishari/Projects/Mapillary/mapillary_tools/python/add_mapillary_tag_from_exif.py", line 67, in <module>
    MAPILLARY_USERNAME, MAPILLARY_EMAIL, None, upload_token, sequence_uuid)
  File "/Users/mishari/Projects/Mapillary/mapillary_tools/python/lib/exifedit.py", line 103, in create_mapillary_description
    metadata = ExifEdit(filename)
  File "/Users/mishari/Projects/Mapillary/mapillary_tools/python/lib/exifedit.py", line 179, in __init__
    self.ef = JpegFile.fromFile(filename)
  File "/Users/mishari/Projects/Mapillary/mapillary_tools/python/lib/pexif.py", line 962, in fromFile
    return JpegFile(f, filename=filename, mode=mode)
  File "/Users/mishari/Projects/Mapillary/mapillary_tools/python/lib/pexif.py", line 1025, in __init__
    attempt = segment_class(mark, input, data, self.mode)
  File "/Users/mishari/Projects/Mapillary/mapillary_tools/python/lib/pexif.py", line 181, in __init__
    raise JpegFile.InvalidFile("Unable to find EOI marker.")
```

**Comment by ybkuang** [comment]
@mishari This is related to the exif library. We have been working on a fix for it. We want to test if the fix works or not on your images. Can you send a few (1-2) sample images to yubin at mapillary dot com

**Comment by maherkarim** [comment]
Dears,
We are facing the same issue with uploading images to mapillary. Please is there any update on this issue

Thanks

**Comment by ybkuang** [comment]
@maherkarim sorry for the delay. We are still investigating and find a stable library for this. The exif libraries are having problem with irregular EXIF fields. Can you also send some samples to us so we can investigate? yubin at mapillary.com

**Comment by mishari** [comment]
@ybkuang sorry it seems I've deleted the bad images, but can you recreate the issue by truncating the image, say by doing dd if=image.jpg output=broken.jpg bs=1m count=1?

**Comment by jernejaMislej** [comment]
@mishari  hi, sorry for not getting back to you on this issue.
we have replaced the exif library, which is now able to handle images like yours, so hopefully you will not experience this issue anymore.

if you have any more problems with your imports please get back to us, otherwise I will close this issue
