### ISSUE TITLE
urlopen errors upload stuck on 0 images left

### ISSUE THREAD

**Issue by andrewharvey** [mapillary/mapillary_tools#250]
### Basic information
* Release version: master
* System: `Linux`
* Capture Device: `Action Camera`

```
Exception in thread Thread-3:--------------------------------] 15.9% ... 132 images left.
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user/.local/lib/python2.7/site-packages/mapillary_tools/uploader.py", line 60, in run
    upload_file(filepath, self.root, **params)
  File "/home/user/.local/lib/python2.7/site-packages/mapillary_tools/uploader.py", line 524, in upload_file
    response = urllib2.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 772, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 659, in read
    v = self._sslobj.read(len)
error: [Errno 104] Connection reset by peer
```

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user/.local/lib/python2.7/site-packages/mapillary_tools/uploader.py", line 60, in run
    upload_file(filepath, self.root, **params)
  File "/home/user/.local/lib/python2.7/site-packages/mapillary_tools/uploader.py", line 524, in upload_file
    response = urllib2.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 772, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 659, in read
    v = self._sslobj.read(len)
error: [Errno 104] Connection reset by peer

URL error: <urlopen error [Errno -3] Temporary failure in name resolution> on DSC06111.JPG
```

Then it's stalled on:

```
[============================================================] 100.0% ... 0 images left.
```

**Comment by jernejaMislej** [comment]
hi, thank you for this, I will have a look and get back to you.

**Comment by jernejaMislej** [comment]
hi,
i had a look at this and the most likely issue is with sending the DONE file, which is equivalent to approving publication of uploaded images. 
Currently the DONE file is send in the end after all the images are uploaded, for each sequence.
I increased the max attempts for the DONE file and implemented a `post_process` command which includes pushing uploading images to be approved.
Generally if images were uploaded, but not approved, one can just run the `upload` command again and it will not re-upload images put just send the DONE file only. so if tools are just hanging there you can interrupt and run again. In some cases of bugs and also unknown issues images can get logged as if already approved for publication, but the DONE file is not successfully uploaded, in those cases the `upload` command will not do anything.
The `post_process` command will approve publication of all images in the specified import path regardless if logs state that it has already been done.
currently that is not the final solution but a temporary work around, as we are planning to improve this in the future releases
pushing images in the specified import path, ie uploading the DONE file will not result in any issues in any case, so you can run the `post_process` command with arg `--push_images` whenever you are not sure if the upload has been approved for publish or are missing uploaded images for a longer period of time

**Comment by andrewharvey** [comment]
Thanks @jernejaMislej you're right, the workaround is to kill the process and run it again where it finishes. Though this becomes an issue when the upload is scripted, or happens in a way without user interaction.

**Comment by jernejaMislej** [comment]
ok i see, yes that can be tedious 
but since it involves uploading it is dependent on the network connection, so it will be hard to implement something to avoid this completely, for now unfortunately if the tools are being called from another script, that script needs to read the return status and (re)run accordingly
you are welcome to contribute if you have any suggestions

**Comment by andrewharvey** [comment]
> that script needs to read the return status and (re)run accordingly

But the script never finishes it just hangs there on 0 images left.

> you are welcome to contribute if you have any suggestions

No worries if it's not a priority to fix. Happy for this bug to sit open until someone can contribute to fixing.

**Comment by ptpt** [comment]
The issue should be gone in 0.7.0. Please upgrade.
