### ISSUE TITLE
"global name 'processing' is not defined" from the "keep original files" feature

### ISSUE THREAD

**Issue by breunigs** [mapillary/mapillary_tools#257]
### Basic information
* Release version: `0.1.0`
* System: `Linux`
* Capture Device: `Action Camera`

### Steps to reproduce behavior

 1. `mapillary_tools process_and_upload --import_path "photos"`
(note that this doesn't even use the keep original files flag)

### Actual behavior

```
Traceback (most recent call last):
  File "/home/stefan/.local/bin/mapillary_tools", line 60, in <module>
    command.run(args)
  File "/home/stefan/.local/lib/python2.7/site-packages/mapillary_tools/commands/process_and_upload.py", line 109, in run
    upload(**({k: v for k, v in vars_args.iteritems()
  File "/home/stefan/.local/lib/python2.7/site-packages/mapillary_tools/upload.py", line 53, in upload
    upload_file_list = [f for f in upload_file_list if verify_mapillary_tag(f)]
  File "/home/stefan/.local/lib/python2.7/site-packages/mapillary_tools/exif_aux.py", line 47, in verify_mapillary_tag
    filepath_keep_original = processing.processed_images_rootpath(filepath)
NameError: global name 'processing' is not defined
```

And if you comment out the broken lines in `exif_aux.py` you'll get this for every image:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/stefan/.local/lib/python2.7/site-packages/mapillary_tools/uploader.py", line 59, in run
    upload_file(filepath, **params)
  File "/home/stefan/.local/lib/python2.7/site-packages/mapillary_tools/uploader.py", line 498, in upload_file
    filepath_keep_original = processing.processed_images_rootpath(filepath)
NameError: global name 'processing' is not defined
```

And if you comment the broken lines here as well, at the end of the upload:

```
  File "/home/stefan/.local/bin/mapillary_tools", line 60, in <module>
    command.run(args)
  File "/home/stefan/.local/lib/python2.7/site-packages/mapillary_tools/commands/process_and_upload.py", line 109, in run
    upload(**({k: v for k, v in vars_args.iteritems()
  File "/home/stefan/.local/lib/python2.7/site-packages/mapillary_tools/upload.py", line 94, in upload
    uploader.finalize_upload(import_path, finalize_params)
  File "/home/stefan/.local/lib/python2.7/site-packages/mapillary_tools/uploader.py", line 145, in finalize_upload
    upload_done_file(import_path, params)
  File "/home/stefan/.local/lib/python2.7/site-packages/mapillary_tools/uploader.py", line 480, in upload_done_file
    upload_file(DONE_filepath, None, **params)
TypeError: upload_file() got multiple values for keyword argument 'url'
```

### Additional information

Worked fine with the previous version.

**Comment by jernejaMislej** [comment]
hi i m sorry for this, i fixed it now, should be ok
