### ISSUE TITLE
upload_with_authentication.py error in thread means stall at the end of process

### ISSUE THREAD

**Issue by smsm1** [mapillary/mapillary_tools#27]
I found the following error

```
Success: VIRB0560.JPG
Uploading: VIRB0562.JPG
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Users/shaunmcdonald/code/mapillary_tools/python/upload.py", line 182, in run
    upload_file(filepath, **self.params)
  File "/Users/shaunmcdonald/code/mapillary_tools/python/upload.py", line 120, in upload_file
    response = urllib2.urlopen(request)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 373, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

Success: VIRB0558.JPG
Uploading: VIRB0563.JPG
```

whilst uploading has meant that after the last file uploaded the python script just stalled and didn't do anything more.

It was sequence "Uploading sequence b14339de-8a17-4eed-aeca-3df14110f068."

There was also the error 

```
URL error: <urlopen error [Errno 32] Broken pipe> on VIRB0301.JPG
```

Which may affect it too. 

Could the script be made to cope with the above error?

**Comment by jesolem** [comment]
Hi @smsm1 
Any suggestion for how to handle the error from the script side?

With the new web uploader you should be able to see such failed uploads as a tab in the photo section. You can then fix/add photos that went wrong and complete the upload. 
Would be great if you could try this next time the script fails and give us feedback.

**Comment by richlv** [comment]
issue #78 seems to be about the same error, although it does not hang there, it just exist

**Comment by jernejaMislej** [comment]
We have released a new version of the tools, instructions and details in the [README](https://github.com/mapillary/mapillary_tools/blob/master/README.md).
Please use the new tools and let us know if you have any issues.

**Comment by richlv** [comment]
Please reopen - seeing the same problem with a recent version.

**Comment by richlv** [comment]
Yes, in this case running plain upload.py; if connection fails in an unhandled way, resulting in a Python exception, that thread stops working on the remaining issues and does not exit when the other threads finish uploading (or hang on exceptions).

**Comment by jernejaMislej** [comment]
thanks for getting back. 
I havent experienced such an issue with the latest tools. Please use the latest release and if you still get such errors, please open a new issue, stating the release, OS, tool etc. and as much information as possible and I will look into it more thoroughly
