### ISSUE TITLE
OverflowError: Python int too large to convert to C long with --convert-gps-time set

### ISSUE THREAD

**Issue by realchrisolin** [mapillary/mapillary_tools#332]
### Basic information
* Release version: `10.0.17763.379`
* System: `Windows` 
* Capture Device: `Action Camera` | `.

### Additional information

```
mapillary_tools process_csv --import_path "/path/to/csv" --timestamp_column 1 --latitude_column 2 --longitude_column 3 --altitude_column 4 --heading_column 5 --gps_week_column 6 --convert_gps_time --advanced
Inserting csv data in image EXIF: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "mapillary_tools", line 76, in <module>
  File "mapillary_tools\commands\process_csv.py", line 49, in run
  File "mapillary_tools\process_csv.py", line 269, in process_csv
  File "mapillary_tools\process_csv.py", line 146, in parse_csv_geotag_data
  File "mapillary_tools\process_csv.py", line 78, in convert_from_gps_time
OverflowError: Python int too large to convert to C long
[17208] Failed to execute script mapillary_tools
```

The CSV file can be provided on request, but I'm pretty sure it's choking on the GPS time value, which is basically epoch time * 10000 or something like that. The values look something like 1535043722000000. Having looked at process_csv.py, and the functions in the traceback log, it looks like this is a moderately significant bug.

### Expected behavior

Command parses info successfully and exits gracefully

### Actual behavior

death, destruction, and mayhem

### Additional information

I don't think any more info is needed to troubleshoot this, but I promise do to my best to respond to requests for more info within 24 hours.

**Comment by jernejaMislej** [comment]
currently microseconds are not supported, only up to milliseconds precision
@josealb we would need to add another check for the divider [here](https://github.com/mapillary/mapillary_tools/blob/a15261b0ad290c6258e0f9b746877ef6ee732f1a/mapillary_tools/process_csv.py#L22) to increase it if microseconds
@realchrisolin we will get back to you as soon as we fix this

**Comment by realchrisolin** [comment]
Sounds good. I can manually adjust the values to be in milliseconds in the meantime.

Not sure if your team uses Agile to help organize tickets, but in case you do and so this is pointed correctly, Garmin's 360° camera generates metadata files with microsecond timing. Adding support for microseconds would allow people with that camera upload without any extra steps.

**Comment by ptpt** [comment]
the command process_csv is removed in v0.8.0 so it's not relevant any more
