### ISSUE TITLE
Unable to run tests locally without mapillary_messi

### ISSUE THREAD

**Issue by Jakuje** [mapillary/mapillary_tools#365]
### Basic information
* Release version: `master`
* System: `Linux`
* Capture Device: `Action Camera`

(but neither above matters)

### Steps to reproduce behavior

 1. Run `python3 setup.py test`

### Expected behavior

The tests are executed and changes are verified.

### Actual behavior

```
test_process_images_provider (unittest.loader._FailedTest) ... ERROR
tests.integration.mapillary_tools_process_images_provider.test_process_images_provider (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_process_images_provider (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_process_images_provider
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/jjelen/devel/mapillary_tools/tests/integration/mapillary_tools_process_images_provider/test_process_images_provider.py", line 6, in <module>
    from mapillary_messi.assertions.harvest_assertions import HarvestAssertion
ModuleNotFoundError: No module named 'mapillary_messi'


======================================================================
ERROR: tests.integration.mapillary_tools_process_images_provider.test_process_images_provider (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.integration.mapillary_tools_process_images_provider.test_process_images_provider
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib64/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/jjelen/devel/mapillary_tools/tests/integration/mapillary_tools_process_images_provider/test_process_images_provider.py", line 6, in <module>
    from mapillary_messi.assertions.harvest_assertions import HarvestAssertion
ModuleNotFoundError: No module named 'mapillary_messi'


----------------------------------------------------------------------
Ran 2 tests in 0.000s

FAILED (errors=2)
Test failed: <unittest.runner.TextTestResult run=2 errors=2 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=2 errors=2 failures=0>
```

**Comment by ptpt** [comment]
It should be fixed. To run the latest tests see https://github.com/mapillary/mapillary_tools#development
