### ISSUE TITLE
mapillary_tools process is not working

### ISSUE THREAD

**Issue by mnigri** [mapillary/mapillary_tools#391]
Hello,

I am having difficulty 

### Basic information
* Mapillary tools version : 0.6.0
* Exiftool version: 12.24
* DashCam: Rove Model R2-4K (with built-in GPS)
* System: Linux – Ubuntu 20.04

### Steps to reproduce behavior

1.	Create GPX file from mp4 metadata:

I have some mp4 files created by the dashcam above. I am using exiftool to extract GPS data and saving them in gpx format running the following command:

    exiftool -p gpx.fmt -ee file.mp4 > file.gpx
    where: gpx.fmt was obtained from https://raw.githubusercontent.com/exiftool/exiftool/master/fmt_files/gpx.fmt.

The gpx file is created successfully, except that there is no altitude information found. There are actually 180 warnings, such as:

    Warning: [Minor] Tag 'Doc1:gpsaltitude' not defined - 2021_0412_172415_007.mp4

I ignored the warnings and carried on.

2.	Video Sampling the mp4/gpx pair of files to create jpg files (2 per second):

I ran the following command:

    mapillary_tools sample_video --import_path image --video_import_path video --video_sample_interval 0.5 --advanced –verbose

where:
    image is the subdirectory where the images are written to
    video is the subdirectory where the mp4/gpx files are read from

No errors. Looking the image subdirectory, I can see that a directory called mapillary_sampled_video_frames is created. Inside it as many subdirectories are created as mp4 files found in the <video> directory. Inside these final subdirectories, several jpg files were created according to the video time and the 0.5 parameter defined above.

Everything seems fine, so far.

3.	Process

I ran the following command:

    mapillary_tools process --advanced --import_path image/mapillary_sampled_video_frames/2021_0412_172415_007 --user_name <myusername> --geotag_source gpx --geotag_source_path video --overwrite_all_EXIF_tags
 
where: 
    image/mapillary_sampled_video_frames/2021_0412_172415_007 is the directory where jpg files are written
    video is the directory where the gpx file is found

### Expected behavior

I was hoping that the process would run until the end

### Actual behavior

Mapillary_tools crashed. The following output was seen after the command in step 3 above:

Running user_process for 362 images, skipping 0 images.
Sub process ended
Running import_meta_data_process for 362 images, skipping 0 images.
Sub process ended
Running geotag_process for 362 images, skipping 0 images.
It is assumed that the image timestamps are in UTC. If not, try using the option --local_time.
Traceback (most recent call last):
  File "<...>/.local/bin/mapillary_tools", line 8, in <module>
    sys.exit(main())
  File "<...>/.local/lib/python3.8/site-packages/mapillary_tools/__main__.py", line 93, in main
    command.run(args)
  File "<...>/.local/lib/python3.8/site-packages/mapillary_tools/commands/process.py", line 389, in run
    process_geotag_properties(
  File "<...>/.local/lib/python3.8/site-packages/mapillary_tools/process_geotag_properties.py", line 97, in process_geotag_properties
    geotag_properties = processing.geotag_from_gps_trace(
  File "<...>/.local/lib/python3.8/site-packages/mapillary_tools/processing.py", line 333, in geotag_from_gps_trace
    gps_trace = get_lat_lon_time_from_gpx(geotag_source_path, local_time)
  File "<...>/.local/lib/python3.8/site-packages/mapillary_tools/gps_parser.py", line 24, in get_lat_lon_time_from_gpx
    with open(gpx_file, "r") as f:
IsADirectoryError: [Errno 21] Is a directory: 'video'

I repeated the above steps with a BlackVue DR-9000S-1-CH camera and the same results were obtained. I also tried using the gpx file created by the mapillary Uploader for Windows App. Same result, 

Any clue where the problem is and how to solve it? I appreciate any help.

Thanks.

**Comment by mnigri** [comment]
I finally found out the error: the parameter --geotag_source_path expects the gpx file and not its directory.

So instead of:

--geotag_source_path  video

I should use:

--geotag_source_path  video/file.gpx
