### ISSUE TITLE
struct.error: 'H' format requires 0 <= number <= 65535

### ISSUE THREAD

**Issue by lionkmp** [mapillary/mapillary_tools#431]
### Basic information

* Release version:   0.7.2
* System: Linux
* Capture Device: Android, photos (not the App)

### Steps to reproduce behavior

I'm not sure if this is important, but there was ONE IMAGE that stopped the process. After I tried again. Again. Then I deleted that one image, and the rest ran OK. The images were taken with an old Samsung Note1, using a timed camera app. I've processed thousands of such images before without this error.

```
mapillary_tools process --advanced --interpolate_directions --overwrite_EXIF_direction_tag --geotag_source exif --rerun --import_path ***** --user_name ****

Running user_process for 1624 images, skipping 0 images.
Logging: 100%| 1624/1624 [00:00<00:00, 4586.91it/s]
Sub process ended
Running import_meta_data_process for 1624 images, skipping 0 images.
Processing image import properties: 100%| 1624/1624 [00:01<00:00, 827.88it/s]
Sub process ended
Running geotag_process for 1624 images, skipping 0 images.
Extracting gps data from image EXIF: 100%|| 1624/1624 [00:02<00:00, 800.94it/s]
Sub process ended
Running sequence_process for 1624 images, skipping 0 images.
Loading geotag points: 100%|| 1624/1624 [00:00<00:00, 6572.88it/s]
Finalizing sequence process: 173it [00:00, 5100.77it/s]
Finalizing sequence process: 487it [00:00, 4288.59it/s]
Finalizing sequence process: 324it [00:00, 5131.13it/s]
Finalizing sequence process: 500it [00:00, 4963.02it/s]
Finalizing sequence process: 138it [00:00, 2538.77it/s]
Finalizing sequence process: 1it [00:00, 4284.27it/s]
Sub process ended
Running upload_params_process for 1624 images, skipping 0 images.
Processing image upload parameters: 100%|| 1624/1624 [00:00<00:00, 2485.41it/s]
Sub process ended
Running mapillary_image_description for 1624 images, skipping 0 images.
Inserting mapillary image description in image EXIF:  23%|████████████████▎                                                      | 372/1624 [00:19<01:04, 19.52it/s]
Traceback (most recent call last):
  File "/home/lion/.local/bin/mapillary_tools", line 8, in <module>
    sys.exit(main())
  File "/home/lion/.local/lib/python3.8/site-packages/mapillary_tools/__main__.py", line 93, in main
    command.run(args)
  File "/home/lion/.local/lib/python3.8/site-packages/mapillary_tools/commands/process.py", line 419, in run
    insert_MAPJson(
  File "/home/lion/.local/lib/python3.8/site-packages/mapillary_tools/insert_MAPJson.py", line 77, in insert_MAPJson
    processing.get_final_mapillary_image_description(
  File "/home/lion/.local/lib/python3.8/site-packages/mapillary_tools/processing.py", line 646, in get_final_mapillary_image_description
    image_exif.write(filename=target)
  File "/home/lion/.local/lib/python3.8/site-packages/mapillary_tools/exif_write.py", line 95, in write
    piexif.insert(exif_bytes, img, filename)
  File "/home/lion/.local/lib/python3.8/site-packages/piexif/_insert.py", line 19, in insert
    exif = b"\xff\xe1" + struct.pack(">H", len(exif) + 2) + exif
struct.error: 'H' format requires 0 <= number <= 65535

```

### Additional information
Command `exiv2 pr 0525.jpg` prints the EXIF, reports no error.

**Comment by ptpt** [comment]
It's likely that the exif library doesn't parse the EXIF correctly. @lionkmp would you mind providing the image for us to debug?

**Comment by lionkmp** [comment]
Yes, thank you, I also think it's a very rare case, but better error handling may be useful. 
I attached it here, but I'm not sure this will keep all EXIF data intact, so I've uploaded it to this URL too:
https://www.openstreetmap.hu/letoltes/kempelen/0525.jpg


![0525](https://user-images.githubusercontent.com/5088657/128978655-7ca08b7a-7d58-487e-b281-9baac76c3261.jpg)
