### ISSUE TITLE
Add option to automatically skip images in video_process_and_upload

### ISSUE THREAD

**Issue by dbdean** [mapillary/mapillary_tools#440]
### Basic information

I'm running the latest version of mapillary_tools straight from the github source, using the docker-compose file (that I created) located at https://github.com/dbdean/mapillary-upload-docker/blob/main/docker-compose.yml.

I'm processing a large volume of images for @bob3bob3 captured using a BlackVue DR900S-1CH.

### Steps to reproduce behavior

Run the following command on a folder containing a large number of videos:

```
INPUT=/path/to/images
MAPILLARY_USER=username
mapillary_tools video_process_and_upload $INPUT \
   --user_name $MAPILLARY_USER \
   --geotag_source "blackvue_videos" \
   --geotag_source_path $INPUT \
   --interpolate_directions \
   --video_sample_interval 0.5 \
   --device_make "Blackvue" \
   --device_model "DR900S-1CH" \
   --overwrite_EXIF_gps_tag \
   --duplicate_distance 1.0 \
```

The process then finishes with an error:

```
Processing import meta properties: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 494315/494315 [1:09:01<00:00, 119.35files/s]
Processing image description: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 494315/494315 [14:21:28<00:00,  9.56files/s]
2021-10-12 04:51:52,801 - INFO   - {
    "total_images": 494315,
    "processed_images": 487268,
    "failed_images": 244,
    "duplicated_images": 6803
}
Traceback (most recent call last):
  File "/usr/local/bin/mapillary_tools", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/mapillary_tools/__main__.py", line 123, in main
    args.func(vars(args))
  File "/usr/local/lib/python3.8/dist-packages/mapillary_tools/commands/video_process_and_upload.py", line 17, in run
    ProcessCommand().run(args)
  File "/usr/local/lib/python3.8/dist-packages/mapillary_tools/commands/process.py", line 251, in run
    insert_MAPJson(
  File "/usr/local/lib/python3.8/dist-packages/mapillary_tools/insert_MAPJson.py", line 135, in insert_MAPJson
    raise RuntimeError(
RuntimeError: Failed to process 244 images. Check to_upload/mapillary_sampled_video_frames/mapillary_image_description.json for details. Specify --skip_process_errors to skip these errors
ERROR: 1
```
**I don't care about this error for this issue, I just want to rerun the process with --skip_process_errors**

So, now rerun the same command but add `--skip_process_errors`

### Expected behavior

That mapillary_tools can gracefully work as a reentrant process that can be stopped and rerun multiple times without having to redo significant processing.

Failing that, an option to automatically answer No to these questions would help. Maybe something like `--skip_already_extracted`

### Actual behavior

The scripts asks me if I want to process every single video again:

```
The sample folder to_upload/mapillary_sampled_video_frames/20210505_120432_NF.mp4 already contains 122 images.
To proceed, either DELETE the whole folder to restart the extraction (y), or skip the extraction (N)? [y/N] ^C
```

Answering this question manually for thousands of videos is not my idea of fun.

**Comment by dbdean** [comment]
@ptpt, I think that would be a good solution.
