### ISSUE TITLE
MT 0.8.0 GoPro problem with 'localtime | use_gps_start_time | offset_time'

### ISSUE THREAD

**Issue by SapozhnikUA** [mapillary/mapillary_tools#452]
* Release version: `0.8.0` 
* System: `Linux` 
* Capture Device: `Action Camera GOPRO`

I had the same problems on previous version MT but it was solved in [ISSUE#424](https://github.com/mapillary/mapillary_tools/issues/424)
But in MT 0.8.0 these arguments aren't available and I again had this problem:
`1. Specify --local_time to read the timestamps from the geotag source file as local time`
`2. Use --use_gps_start_time to align the start time`

command which I use:
`mapillary_tools video_process_and_upload "$VIDEO_PATH" "$IMG_PATH" --user_name sapozhnik --geotag_source "gopro_videos" --geotag_source_path "$VIDEO_PATH" --interpolate_directions --video_sample_interval 0.5 --overwrite_EXIF_gps_tag`
Sample of video: [file MP4, 66Mb](https://stat.waze.com.ua/temp/GH014221.MP4)
Mapillary_image_description.json with errors : [JSON](https://stat.waze.com.ua/temp/mapillary_image_description.json)

Copy of all information:
```
Video path: /home/andrey/mapillary/video/
IMG folder: /mnt/drive_d/mapillary/img/
2021-10-17 18:23:42,797 - INFO   - Extracting video information: ffmpeg -i /home/andrey/mapillary/video/GH014221.MP4 -vf fps=1/0.5
-qscale:v 1 -nostdin /mnt/drive_d/mapillary/img/GH014221.MP4.21173.1634473422/GH014221_%06d.jpg
ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/inc
lude/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enab
le-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-l
ibfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable
-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enabl
e-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libw
avpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-o
penal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --
enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/andrey/mapillary/video/GH014221.MP4':
  Metadata:
    major_brand     : mp41
    minor_version   : 538120216
    compatible_brands: mp41
    creation_time   : 2021-06-12T16:47:20.000000Z
    location        : +50.4239+029.6801/
    location-eng    : +50.4239+029.6801/
    firmware        : HD7.01.01.90.00
  Duration: 00:00:12.10, start: 0.000000, bitrate: 45455 kb/s
    Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 45242 kb/s, 50 fps
, 50 tbr, 90k tbn, 100 tbc (default)
    Metadata:
      rotate          : 180
      creation_time   : 2021-06-12T16:47:20.000000Z
      handler_name    : GoPro AVC
      encoder         : GoPro AVC encoder
      timecode        : 00:59:20:14
    Side data:
      displaymatrix: rotation of -180.00 degrees
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 188 kb/s (default)
    Metadata:
      creation_time   : 2021-06-12T16:47:20.000000Z
      handler_name    : GoPro AAC
      timecode        : 00:59:20:14
    Stream #0:2(eng): Data: none (tmcd / 0x64636D74), 0 kb/s (default)
    Metadata:
      creation_time   : 2021-06-12T16:47:20.000000Z
      handler_name    : GoPro TCD
      timecode        : 00:59:20:14
    Stream #0:3(eng): Data: none (gpmd / 0x646D7067), 42 kb/s (default)
    Metadata:
      creation_time   : 2021-06-12T16:47:20.000000Z
      handler_name    : GoPro MET
    Stream #0:4(eng): Data: none (fdsc / 0x63736466), 13 kb/s (default)
    Metadata:
      creation_time   : 2021-06-12T16:47:20.000000Z
      handler_name    : GoPro SOS
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> mjpeg (native))
Output #0, image2, to '/mnt/drive_d/mapillary/img/GH014221.MP4.21173.1634473422/GH014221_%06d.jpg':
  Metadata:
    major_brand     : mp41
    minor_version   : 538120216
    compatible_brands: mp41
    firmware        : HD7.01.01.90.00
    location        : +50.4239+029.6801/
    location-eng    : +50.4239+029.6801/
    encoder         : Lavf57.83.100
    Stream #0:0(eng): Video: mjpeg, yuvj420p(pc), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 2 fps, 2 tbn, 2 tbc (default)
    Metadata:
      encoder         : Lavc57.107.100 mjpeg
      creation_time   : 2021-06-12T16:47:20.000000Z
      handler_name    : GoPro AVC
      timecode        : 00:59:20:14
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
      displaymatrix: rotation of -0.00 degrees
frame=   24 fps=7.1 q=1.0 Lsize=N/A time=00:00:12.00 bitrate=N/A speed=3.57x
video:6983kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
2021-10-17 18:23:46,265 - INFO   - Extracting video information: ffprobe -print_format json -loglevel quiet -show_streams /home/and
rey/mapillary/video/GH014221.MP4
2021-10-17 18:23:46,391 - INFO   - Extracting video information: ffprobe -print_format json -loglevel quiet -show_format -show_streams /home/andrey/mapillary/video/GH014221.MP4
2021-10-17 18:23:46,485 - INFO   - Extracting video information: ffmpeg -i /home/andrey/mapillary/video/GH014221.MP4 -y -nostats -loglevel 0 -codec copy -map 0:3 -f rawvideo /tmp/tmp1rh1q4_h


2021-10-17 18:23:46,596 - INFO   - {
    "total_images": 24,
    "processed_images": 0,
    "failed_images": 24,
    "duplicated_images": 0
}


Traceback (most recent call last):
  File "/usr/local/bin/mapillary_tools", line 11, in <module>
    load_entry_point('mapillary-tools==0.8.0', 'console_scripts', 'mapillary_tools')()
  File "/usr/local/lib/python3.6/dist-packages/mapillary_tools/__main__.py", line 123, in main
    args.func(vars(args))
  File "/usr/local/lib/python3.6/dist-packages/mapillary_tools/commands/video_process_and_upload.py", line 17, in run
    ProcessCommand().run(args)
  File "/usr/local/lib/python3.6/dist-packages/mapillary_tools/commands/process.py", line 275, in run
    for k, v in vars_args.items()
  File "/usr/local/lib/python3.6/dist-packages/mapillary_tools/process_geotag_properties.py", line 228, in insert_MAPJson
    f"Failed to process {summary['failed_images']} images. Check {desc_path} for details. Specify --skip_process_errors to skip the
se errors"
RuntimeError: Failed to process 24 images. Check /mnt/drive_d/mapillary/img/mapillary_image_description.json for details. Specify -
-skip_process_errors to skip these errors
```

**Comment by ptpt** [comment]
@SapozhnikUA

* `--use_gps_start_time` is renamed to `--interpolation_use_gpx_start_time`
* `--local_time` is replaced by `--interpolation_offset_time`


```
mapillary_tools video_process --help

  --interpolation_use_gpx_start_time
                        If supplied, the first image will use the first GPX
                        point time for interpolation, which means the image
                        location will be interpolated to the first GPX point
                        too. Applicable for geotagging from gpx, gopro_videos,
                        nmea, blackvue_videos
  --interpolation_offset_time INTERPOLATION_OFFSET_TIME
                        Time offset, in seconds, that be added for GPX
                        interpolation, which affects image locations. Note
                        that it is applied after
                        --interpolation_use_gpx_start_time. Applicable for
                        geotagging from gpx, gopro_videos, nmea,
                        blackvue_videos
```

**Comment by SapozhnikUA** [comment]
@ptpt 
Thanks!!! 
It helps me.
