### ISSUE TITLE
Mapillary tools crashes when using ZScaler Proxy

### ISSUE THREAD

**Issue by Mr-Technician** [mapillary/mapillary_tools#522]
### Basic information
* Release version: `0.9.0`
* System: `Windows`
* Capture Device: `Ricoh Theta V`

### Steps to reproduce behavior

I get an SSL error  when using mapillary tools behind a Zscaler proxy.
 1. Launch mapillary with `./mapillary.exe authenticate`
 2. Type in credentials
 3. Wait for it to crash

### Expected behavior

The login/upload should work regardless of proxy and without needing to whitelist addresses in Zscaler.

### Actual behavior

An SSL error occurs, see below. The error was resolved by contacting the IT administrators who added `rupload.facebook.com` and `graph.mapillary.com` to the Zscaler exception list, therefore bypassing SSL inspection.

### Corresponding data

```
PS C:\mapillary> ./mapillary_tools-0.9.0-win-64bit authenticate
Enter the Mapillary username you would like to (re)authenticate: redacted
Sign in for user redacted
Enter your Mapillary user email: redacted
Enter Mapillary user password:
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 703, in urlopen
  File "urllib3\connectionpool.py", line 386, in _make_request
  File "urllib3\connectionpool.py", line 1042, in _validate_conn
  File "urllib3\connection.py", line 414, in connect
  File "urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 489, in send
  File "urllib3\connectionpool.py", line 787, in urlopen
  File "urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='graph.mapillary.com', port=443): Max retries exceeded with url: /login?access_token=token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "mapillary_tools\commands\__main__.py", line 127, in main
  File "mapillary_tools\commands\authenticate.py", line 32, in run
  File "mapillary_tools\authenticate.py", line 41, in authenticate
  File "mapillary_tools\authenticate.py", line 66, in prompt_user_for_user_items
  File "mapillary_tools\api_v4.py", line 22, in get_upload_token
  File "requests\api.py", line 115, in post
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 587, in request
  File "requests\sessions.py", line 701, in send
  File "requests\adapters.py", line 563, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='graph.mapillary.com', port=443): Max retries exceeded with url: /login?access_token=token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
[12296] Failed to execute script 'main' due to unhandled exception!
```

### Additional information

I'm guessing the python module that handles networking doesn't like something with the Zscaler proxy, which needs to issue its own local SSL cert to make SSL inspection possible.

**Comment by ptpt** [comment]
Could you reproduce the issue with the pip installed one?

**Comment by Mr-Technician** [comment]
Let me see, I have asked for the SSL exceptions to be removed temporarily and will get back to you.

**Comment by Mr-Technician** [comment]
@ptpt I am 99% certain Mapillary is not at fault here. I get a similar SSL error installing mapillary through PIP:
```
PS C:\> python -m pip install --upgrade git+https://github.com/mapillary/mapillary_tools
Collecting git+https://github.com/mapillary/mapillary_tools
  Cloning https://github.com/mapillary/mapillary_tools to c:\users\rnielsen\appdata\local\temp\pip-req-build-f68asnu2
  ERROR: Error [WinError 2] The system cannot find the file specified while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)'))) - skipping
WARNING: There was an error checking the latest version of pip.
```
I realize that git not being installed is part of the issue but the SSL issue is more glaring.

I found this from Zscaler: https://community.zscaler.com/t/installing-tls-ssl-root-certificates-to-non-standard-environments/7261?page=2#:~:text=get%20http.sslcainfo)-,Python,-Python%20on%20Windows

I think this explains my issue.

**Comment by RuikangSun** [comment]
Similar issue using proxy to upload images. In addition, with proxy, Mapillary Uploader cannot work properly, too.

**Comment by Mr-Technician** [comment]
@RuikangSun I would guess this is still an internal issue with python and nothing that concerns Mapillary.
