### ISSUE TITLE
RICOH THETA X 1.20.0 8K/2FPS video mode can't upload to mapillary

### ISSUE THREAD

**Issue by mapconcierge** [mapillary/mapillary_tools#536]
### Basic information
* Release version: `0.9.1`
* System: `macOS 12.0.1`
* Capture Device: `Ricoh THETA X 1.20.0`

### Steps to reproduce behavior

 1. THETA X, 8K/2FPS mode
 2. Take a video.
 3. Copy mp4 file to PC(mac)
 4. run **% mapillary_tools video_process "." --geotag_source "camm"** command
 5. **"UDTA parsing failed retrying raw"** and some error happened.
 6. Generated "mapillary_sampled_video_frames" folder has separated jpg files, but those files doesn't have Exif lat/lon metadata

<img width="272" alt="スクリーンショット 2022-08-27 8 46 55" src="https://user-images.githubusercontent.com/416977/187018696-a8439d5e-c031-4e57-9250-a8339d1c625a.png">

### Expected behavior

...

### Actual behavior

```
taichi@TaichinoMBP7290 mapillary_tools % ls
R0020635.MP4
taichi@TaichinoMBP7290 mapillary_tools % mapillary_tools video_process "." --geotag_source "camm"
2022-08-27 08:23:11,260 - INFO    - Extracting video information: ffprobe -print_format json -hide_banner -show_format -show_streams R0020635.MP4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x141e05690] UDTA parsing failed retrying raw
    Last message repeated 1 times
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x141e05690] DTS discontinuity in stream 2: packet 352 with DTS 872625792, packet 353 with DTS 877611198
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'R0020635.MP4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2022-08-27T05:46:56.000000Z
    com.apple.quicktime.location.ISO6709: +43.7696+011.2545+0052/
    com.apple.quicktime.make: RICOH
    com.apple.quicktime.model: RICOH THETA X
    make            : RICOH
    model           : RICOH THETA X
  Duration: 00:02:16.13, start: 0.000000, bitrate: 16680 kb/s
  Stream #0:0[0x1](eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, mono, fltp, 255 kb/s (default)
    Metadata:
      creation_time   : 2022-08-27T05:46:56.000000Z
      handler_name    : SoundHandle
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](eng): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuvj420p(pc, bt470bg/bt709/smpte170m, progressive), 7680x3840, 16221 kb/s, SAR 1:1 DAR 2:1, 2 fps, 2 tbr, 90k tbn (default)
    Metadata:
      creation_time   : 2022-08-27T05:46:56.000000Z
      handler_name    : VideoHandle
      vendor_id       : [0][0][0][0]
    Side data:
      spherical: equirectangular (0.000000/0.000000/0.000000) 
  Stream #0:2[0x3](und): Data: none (camm / 0x6D6D6163), 572881 kb/s (default)
    Metadata:
      creation_time   : 2022-08-27T05:46:56.000000Z
      handler_name    : CameraMetadataMotionHandler
Unsupported codec with id 0 for input stream 2
2022-08-27 08:23:19,150 - INFO    - Extracting frames: ffmpeg -i R0020635.MP4 -vf fps=1/2.0 -hide_banner -qscale:v 1 -nostdin mapillary_sampled_video_frames/.mly_ffmpeg_R0020635.MP4.23352.1661581399/R0020635_%06d.jpg
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x13d704500] UDTA parsing failed retrying raw
    Last message repeated 1 times
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x13d704500] DTS discontinuity in stream 2: packet 352 with DTS 872625792, packet 353 with DTS 877611198
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'R0020635.MP4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2022-08-27T05:46:56.000000Z
    com.apple.quicktime.location.ISO6709: +43.7696+011.2545+0052/
    com.apple.quicktime.make: RICOH
    com.apple.quicktime.model: RICOH THETA X
    make            : RICOH
    model           : RICOH THETA X
  Duration: 00:02:16.13, start: 0.000000, bitrate: 16680 kb/s
  Stream #0:0[0x1](eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, mono, fltp, 255 kb/s (default)
    Metadata:
      creation_time   : 2022-08-27T05:46:56.000000Z
      handler_name    : SoundHandle
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](eng): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuvj420p(pc, bt470bg/bt709/smpte170m, progressive), 7680x3840, 16221 kb/s, SAR 1:1 DAR 2:1, 2 fps, 2 tbr, 90k tbn (default)
    Metadata:
      creation_time   : 2022-08-27T05:46:56.000000Z
      handler_name    : VideoHandle
      vendor_id       : [0][0][0][0]
    Side data:
      spherical: equirectangular (0.000000/0.000000/0.000000) 
  Stream #0:2[0x3](und): Data: none (camm / 0x6D6D6163), 572881 kb/s (default)
    Metadata:
      creation_time   : 2022-08-27T05:46:56.000000Z
      handler_name    : CameraMetadataMotionHandler
Stream mapping:
  Stream #0:1 -> #0:0 (h264 (native) -> mjpeg (native))
Output #0, image2, to 'mapillary_sampled_video_frames/.mly_ffmpeg_R0020635.MP4.23352.1661581399/R0020635_%06d.jpg':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    model           : RICOH THETA X
    com.apple.quicktime.location.ISO6709: +43.7696+011.2545+0052/
    com.apple.quicktime.make: RICOH
    com.apple.quicktime.model: RICOH THETA X
    make            : RICOH
    encoder         : Lavf59.27.100
  Stream #0:0(eng): Video: mjpeg, yuvj420p(pc, bt470bg/bt709/smpte170m, progressive), 7680x3840 [SAR 1:1 DAR 2:1], q=2-31, 200 kb/s, 0.50 fps, 0.50 tbn (default)
    Metadata:
      creation_time   : 2022-08-27T05:46:56.000000Z
      handler_name    : VideoHandle
      vendor_id       : [0][0][0][0]
      encoder         : Lavc59.37.100 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: N/A
      spherical: equirectangular (0.000000/0.000000/0.000000) 
frame=   68 fps= 17 q=1.0 Lsize=N/A time=00:02:16.00 bitrate=N/A speed=33.5x    
video:104173kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/mapillary_tools", line 33, in <module>
    sys.exit(load_entry_point('mapillary-tools==0.9.0', 'console_scripts', 'mapillary_tools')())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mapillary_tools/commands/__main__.py", line 127, in main
    args.func(argvars)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mapillary_tools/commands/video_process.py", line 15, in run
    ProcessCommand().run(args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mapillary_tools/commands/process.py", line 258, in run
    descs = process_geotag_properties(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mapillary_tools/process_geotag_properties.py", line 175, in process_geotag_properties
    return list(types.map_descs(validate_and_fail_desc, geotag.to_description()))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mapillary_tools/geotag/geotag_from_camm.py", line 48, in to_description
    points = camm_parser.parse_gpx(video)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mapillary_tools/geotag/camm_parser.py", line 103, in parse_gpx
    points = list(_extract_delta_points(fp, camm_samples))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mapillary_tools/geotag/camm_parser.py", line 71, in _extract_delta_points
    for sample in samples:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mapillary_tools/geotag/camm_parser.py", line 98, in <genexpr>
    camm_samples = (
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mapillary_tools/geotag/simple_mp4_parser.py", line 531, in parse_samples_from_trak
    for sample in parse_samples_from_stbl(s, maxsize=h.maxsize):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mapillary_tools/geotag/simple_mp4_parser.py", line 518, in parse_samples_from_stbl
    yield from extract_samples(descriptions, raw_samples)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mapillary_tools/geotag/simple_mp4_parser.py", line 459, in extract_samples
    for raw_sample in raw_samples:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mapillary_tools/geotag/simple_mp4_parser.py", line 409, in extract_raw_samples
    assert len(sizes) == len(
AssertionError: sample sizes 54733 and sample times 54732 must have equal length
taichi@TaichinoMBP7290 mapillary_tools % 

```

### Corresponding data

* sample video
https://drive.google.com/drive/folders/1Vye_9wZVzNS4u9W6HfCS7UTDOuPlo9gz?usp=sharing

...

### Additional information

... 

<img width="1512" alt="スクリーンショット 2022-08-27 8 53 32" src="https://user-images.githubusercontent.com/416977/187018805-40eb98df-b464-4588-9e37-4a0a1d517663.png">

<img width="821" alt="スクリーンショット 2022-08-27 8 54 28" src="https://user-images.githubusercontent.com/416977/187018833-8c235f9e-fd8b-4d9f-bd6b-44b7011bafd3.png">

**Comment by ptpt** [comment]
Should be fixed in the PR. Try it out with the latest commit:
```
python3 -m pip install --force-reinstall --upgrade git+https://github.com/mapillary/mapillary_tools
```
Reopen if it doesn't work.

Thanks a lot for the detailed report and the sample videos. The sample videos are very useful!

**Comment by mapconcierge** [comment]
Thanks for your great support! @ptpt 

I've published this approach as blog.
https://medium.com/furuhashilab/theta-x%E3%81%AE2-10fps%E3%83%A2%E3%83%BC%E3%83%89%E3%82%92%E6%A5%B5%E3%82%81%E3%81%97%E8%80%85%E3%81%8Cmapillary%E3%82%92%E5%88%B6%E3%81%99%E3%82%8B-c27e2f95a813
