### ISSUE TITLE
[Regression] SOCKS/proxy support broken

### ISSUE THREAD

**Issue by GITNE** [mapillary/mapillary_tools#566]
### Basic information
* Release version: `0.8.1` to `0.9.4`
* System: `Linux`
* Capture Device: *`any`*

### Steps to reproduce behavior

 1. Configure a SOCKS proxy on your LAN (or choose a public one on the internet; though not recommended).
 2. Set `all_proxy` and/or `ALL_PROXY` to `socks://<proxy_ip>:<proxy_port>`.
 3. Try to upload images with either `upload`, `upload_camm`, `upload_blackvue`, `upload_zip`, `process_and_upload`, or `video_process_and_upload`.

### Expected behavior

`mapillary_tools` should upload zips/images just like in previous versions.

### Actual behavior
```
2022-10-12 10:12:05,381 - WARNING - Error from API Logging for action upload_failed_upload
Traceback (most recent call last):
  File "mapillary_tools/upload.py", line 785, in _upload_zipfiles
  File "mapillary_tools/uploader.py", line 140, in upload_zipfile
  File "mapillary_tools/uploader.py", line 362, in _upload_zipfile_fp
  File "mapillary_tools/uploader.py", line 514, in _upload_fp
  File "mapillary_tools/uploader.py", line 480, in _upload_fp
  File "mapillary_tools/upload_api_v4.py", line 80, in fetch_offset
  File "requests/api.py", line 73, in get
  File "requests/api.py", line 59, in request
  File "requests/sessions.py", line 587, in request
  File "requests/sessions.py", line 701, in send
  File "requests/adapters.py", line 456, in send
  File "requests/adapters.py", line 352, in get_connection
  File "requests/adapters.py", line 217, in proxy_manager_for
  File "requests/adapters.py", line 62, in SOCKSProxyManager
requests.exceptions.InvalidSchema: Missing dependencies for SOCKS support.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mapillary_tools/upload.py", line 618, in upload
  File "mapillary_tools/upload.py", line 789, in _upload_zipfiles
mapillary_tools.upload.UploadError: Missing dependencies for SOCKS support.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mapillary_tools/upload.py", line 457, in _api_logging_failed
  File "mapillary_tools/api_v4.py", line 58, in logging
  File "requests/api.py", line 115, in post
  File "requests/api.py", line 59, in request
  File "requests/sessions.py", line 587, in request
  File "requests/sessions.py", line 701, in send
  File "requests/adapters.py", line 456, in send
  File "requests/adapters.py", line 352, in get_connection
  File "requests/adapters.py", line 217, in proxy_manager_for
  File "requests/adapters.py", line 62, in SOCKSProxyManager
requests.exceptions.InvalidSchema: Missing dependencies for SOCKS support.
Traceback (most recent call last):
  File "mapillary_tools/upload.py", line 785, in _upload_zipfiles
  File "mapillary_tools/uploader.py", line 140, in upload_zipfile
  File "mapillary_tools/uploader.py", line 362, in _upload_zipfile_fp
  File "mapillary_tools/uploader.py", line 514, in _upload_fp
  File "mapillary_tools/uploader.py", line 480, in _upload_fp
  File "mapillary_tools/upload_api_v4.py", line 80, in fetch_offset
  File "requests/api.py", line 73, in get
  File "requests/api.py", line 59, in request
  File "requests/sessions.py", line 587, in request
  File "requests/sessions.py", line 701, in send
  File "requests/adapters.py", line 456, in send
  File "requests/adapters.py", line 352, in get_connection
  File "requests/adapters.py", line 217, in proxy_manager_for
  File "requests/adapters.py", line 62, in SOCKSProxyManager
requests.exceptions.InvalidSchema: Missing dependencies for SOCKS support.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 8, in <module>
  File "mapillary_tools/commands/__main__.py", line 141, in main
  File "mapillary_tools/commands/upload_zip.py", line 32, in run
  File "mapillary_tools/upload.py", line 623, in upload
  File "mapillary_tools/upload.py", line 618, in upload
  File "mapillary_tools/upload.py", line 789, in _upload_zipfiles
mapillary_tools.upload.UploadError: Missing dependencies for SOCKS support.
[771714] Failed to execute script 'main' due to unhandled exception!
```

### Additional information

:cry: I wish the web uploader would come back. Life was much simpler back then.

**Comment by GITNE** [comment]
FYI: The last version to properly work with a SOCKS proxy was 0.8.0.

**Comment by ptpt** [comment]
Hey @GITNE 

I installed this missing package and it works:
```
python3 -m pip install pysocks
```

See https://stackoverflow.com/a/44353599

**Comment by ptpt** [comment]
requests used PySocks under the hood: https://github.com/Anorov/PySocks#proxying-http-traffic

and I guess requests removed it as dependency at a certain point (can't find in CHANGELOG)

**Comment by GITNE** [comment]
> I installed this missing package and it works:

Anyways, then it should be included in the AppImage.

> and I guess requests removed it as dependency at a certain point (can't find in CHANGELOG)

:thinking: Hmm, I do not think so. I would guess that rather either AppImage building has been broken (someone forgot to add PySocks to the AppImage build) or the AppImage build process was moved to a different/new machine that simply lacks the PySocks dependecy.

**Comment by ptpt** [comment]
Let me know if the new builds fix the socks library https://github.com/mapillary/mapillary_tools/releases/tag/v0.9.5a

**Comment by GITNE** [comment]
See https://github.com/mapillary/mapillary_tools/pull/567#issuecomment-1277141663
