### ISSUE TITLE
Something seems to go wrong when finalising the upload with upload_with_authentication.py

### ISSUE THREAD

**Issue by Skippern** [mapillary/mapillary_tools#59]
I get the following when finalising an upload with **upload_with_authentication.py**

Mac OS X 10.10.4, macports, python2.7, all dependencies updated with pip

```
Finalizing upload will submit all successful uploads and ignore all failed.
If all files were marked as successful, everything is fine, just press 'y'.
Finalize upload? [y/n]: y
Upload a DONE file to tell the backend that the sequence is all uploaded and ready to submit.
Uploading: DONE
Success: DONE
Traceback (most recent call last):
  File "upload_with_authentication.py", line 173, in <module>
    upload_done_file(params)
  File "upload_with_authentication.py", line 49, in upload_done_file
    os.remove("DONE")
OSError: [Errno 2] No such file or directory: 'DONE'
```

**Comment by jesolem** [comment]
Ah. I see the problem. If you have move files to True, that parameter is ignored in the check before trying to delete DONE. (the DONE file was moved before the script tries to delete it)

Fixing.
