### ISSUE TITLE
pip install fails on Python 3.12

### ISSUE THREAD

**Issue by 2hu4u** [mapillary/mapillary_tools#674]
Hi there
I am using a fresh install of Python 3.12 with pip 24.0.
Using `pip install mapillary_tools` fails with the following output;

```
Collecting pynmea2==1.12.0 (from mapillary_tools)
  Downloading pynmea2-1.12.0.tar.gz (26 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "C:\Program Files\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Program Files\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\22105466\AppData\Local\Temp\pip-build-env-n0vvx2ob\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\22105466\AppData\Local\Temp\pip-build-env-n0vvx2ob\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\22105466\AppData\Local\Temp\pip-build-env-n0vvx2ob\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\22105466\AppData\Local\Temp\pip-build-env-n0vvx2ob\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 3, in <module>
      ModuleNotFoundError: No module named 'imp'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

It appears that this is a depreciation issue with `imp` which was depreciated in 3.12 but I am not entirely sure.
mapillary_tools installs correctly using the same pip method on Python 3.11 and Python 3.9. I tried this with a few other PCs with Windows 10 and Windows 11, same thing happens across all.

**Comment by ptpt** [comment]
GH actions work. I wonder if it's because of any recent changes. Let me trigger it again and update you here.

**Comment by blaueente** [comment]
same here

**Comment by OnurKader** [comment]
Possible related issue: https://github.com/Knio/pynmea2/issues/163

**Comment by ptpt** [comment]
Should be fixed in https://pypi.org/project/mapillary-tools/0.11.2/

Please try again.
