### ISSUE TITLE
exception - BadStatusLine: ''

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_tools#78]
sometimes uploading fails with an exception like this:
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/rich/files/mapillary/mapillary_tools/python/upload.py", line 187, in run
    upload_file(filepath, **self.params)
  File "/home/rich/files/mapillary/mapillary_tools/python/upload.py", line 120, in upload_file
    response = urllib2.urlopen(request)
  File "/usr/lib64/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib64/python2.7/httplib.py", line 1067, in getresponse
    response.begin()
  File "/usr/lib64/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python2.7/httplib.py", line 373, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''
```

**Comment by richlv** [comment]
still happens repeatedly. especially sad when it happens for the "DONE" file :)
```
Uploading: DONE
Traceback (most recent call last):
  File "/home/rich/files/mapillary/mapillary_tools/python/upload_with_authentication.py", line 189, in <module>
    upload_done_file(params)
  File "/home/rich/files/mapillary/mapillary_tools/python/upload_with_authentication.py", line 52, in upload_done_file
    upload_file("DONE", **params)
  File "/home/rich/files/mapillary/mapillary_tools/python/upload.py", line 119, in upload_file
    response = urllib2.urlopen(request)
  File "/usr/lib64/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib64/python2.7/httplib.py", line 1067, in getresponse
    response.begin()
  File "/usr/lib64/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python2.7/httplib.py", line 373, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''
```

**Comment by richlv** [comment]
might be the same as issue #27

**Comment by ybkuang** [comment]
Closing this and referring to #27.
